export const earthuntAsciiArt =`
sssssssssssssssssssssssssssssssssssssssssss..s...........sssssssssssssssssssssssssssssssssssssssssss
sssssssssssssssssssssssssssssssssssssssss.....::-----::....sssssssssssssssssssssssssssssssssssssssss
sssssssssssssssssssssssssssssssss......:=+#%%%%%%%%%%%%%%%#*=:.....sssssssssssssssssssssssssssssssss
sssssssssssssssssssssssssssssssss..:+#%%%%%%###*++++*+*#%%%%%%%#*-.sssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssss..:*%%%%%*:.-=*-=*+===-:====--+#%%%%%*:.....ssssssssssssssssssssssssss
ssssssssssssssssssssssssss....-%%%%#=.:===+*=--==-::-======-:===*%%%%%=......sssssssssssssssssssssss
ssssssssssssssssssssssssss..=%%%#=::===+**#+=-:=========-:-=:==++++*%%%%+....sssssssssssssssssssssss
sssssssssssssssssssssss...-#%%#=:-==-==*::-=-:.-=====--=+**++**+++*#*#%%%%=..sssssssssssssssssssssss
sssssssssssssssssssssss..+%%%=:-==========++=============--=**+***+++*+*%%%#:.ssssssssssssssssssssss
ssssssssssssssssssss...:#%%*:-=========***#+===========+++###+++++-+++#**%%%#-..ssssssssssssssssssss
ssssssssssssssssssss..-#%%+:=======+##+========++===+#*+**++++++++++***==*#%%%-.ssssssssssssssssssss
ssssssssssssssssssss.:#%%=:======+##===========++=+++:...:+++=-::-:::::=++*#%%%-.sssssssssssssssssss
ssssssssssssssssssss.#%%=:==++=+*##*+++++++*++**#*+++-...=+****+++++++++++**#%%%:...ssssssssssssssss
sssssssssssssssssss.+%%+:++*++#*+=:+***#*********.:--:...---...=+++++++++***##%%#...ssssssssssssssss
ssssssssssssssss...:%%#-+%*++%+==-=*******##****#:..............=++++=++*****#%%%=..ssssssssssssssss
ssssssssssssssss...*%%+-#+++++:::=**********#%##%=sss....:--...:++++++++*****##%%#..ssssssssssssssss
ssssssssssssssss...%%%==+::-=+*#*******=***#=.....sss...-++++++++++++++******##%%#-.ssssssssssssssss
sssssssssssssssss.-%%%++++==+-=+++*****+***#=.....sss...-***#***++++++***######%%%=.ssssssssssssssss
ssssssssssssssss..-%%%*++++*++=+++**####+=+*#*+*#-sss.....::....++++++**###**##%%%=.ssssssssssssssss
sssssssssssssssss.-%%%*++++=-----=*#####+#*#####%:ssssssssssss..=++*++*##****##%%%=.ssssssssssssssss
ssssssssssssssss..:%%%#*++++++++++==-#%#-##*#%##*:-=+:...==-..:=+****+*#*****%%%%%-.ssssssssssssssss
ssssssssssssssss...#%%*-::::=++++*%%%%##########*####-...=###=---=+****##***##%%%#:sssssssssssssssss
ssssssssssssssss...+%%#*++++-++++++++*##########*###*:...-###******=+**###**##%%%*..ssssssssssssssss
ssssssssssssssss....%%%*+++=-+**+++++++====+####*#####+=*####**=**-=**#####*#%%%%-..ssssssssssssssss
ssssssssssssssssss..=%%%***=-++++++**+++++++####*############*+=+*-+*########%%%*...ssssssssssssssss
ssssssssssssssssssss.*%%%***=**++++++++=.-+*%###*#####*-*#%%#***--+*#####*##%%%%....ssssssssssssssss
ssssssssssssssssssss.:#%%%******#***+**++*#%%##%*#######%%%%%**==**###%#*#%%%%%:.sssssssssssssssssss
ssssssssssssssssssss..:#%%%#*****##******######%#####%%%%%%%%#*-+******#%%%%%#-.ssssssssssssssssssss
sssssssssssssssssssss...*%%%%##***##*****##%%##*==***#%%#===+*++***###%%%%%%#:..ssssssssssssssssssss
sssssssssssssssssssssss..=%%%%#############*++******#%%%#+***##%%%%%%%%%%%%+....ssssssssssssssssssss
sssssssssssssssssssssss...:*%%%%###########***+***+**#%%*+*##%%#+%%%%%%%%#:..sssssssssssssssssssssss
sssssssssssssssssssssss.....-#%%%%%######%****=**********#%%%%%%%%%%%%%#-....sssssssssssssssssssssss
sssssssssssssssssssssssssss....#%%%%%#####***********##%%%%%%%%%%%%%%%:..sssssssssssssssssssssssssss
sssssssssssssssssssssssssssssss..=#%%%%%%#%%%###%%%%%%%%%%%%%%%%%%#+..ssssssssssssssssssssssssssssss
sssssssssssssssssssssssssssssssss...-*#%%%%%%%%%%%%%%%%%%%%%%%#*=.....ssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssss..:-+*#%%%%%%%%%%%#*+=:...ssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssss........................`