export const earthuntAsciiArt =`
sssssssssssssssssssssssssss..s...........sssssssssssssssssssssssssssssssssssssssssss
sssssssssssssssssssssssss.....::-----::....sssssssssssssssssssssssssssssssssssssssss
sssssssssssssssss......:=+#%%%%%%%%%%%%%%%#*=:.....sssssssssssssssssssssssssssssssss
sssssssssssssssss..:+#%%%%%%###*++++*+*#%%%%%%%#*-.sssssssssssssssssssssssssssssssss
ssssssssssssss..:*%%%%%*:.-=*-=*+===-:====--+#%%%%%*:.....ssssssssssssssssssssssssss
ssssssssss....-%%%%#=.:===+*=--==-::-======-:===*%%%%%=......sssssssssssssssssssssss
ssssssssss..=%%%#=::===+**#+=-:=========-:-=:==++++*%%%%+....sssssssssssssssssssssss
sssssss...-#%%#=:-==-==*::-=-:.-=====--=+**++**+++*#*#%%%%=..sssssssssssssssssssssss
sssssss..+%%%=:-==========++=============--=**+***+++*+*%%%#:.ssssssssssssssssssssss
ssss...:#%%*:-=========***#+===========+++###+++++-+++#**%%%#-..ssssssssssssssssssss
ssss..-#%%+:=======+##+========++===+#*+**++++++++++***==*#%%%-.ssssssssssssssssssss
ssss.:#%%=:======+##===========++=+++:...:+++=-::-:::::=++*#%%%-.sssssssssssssssssss
ssss.#%%=:==++=+*##*+++++++*++**#*+++-...=+****+++++++++++**#%%%:...ssssssssssssssss
sss.+%%+:++*++#*+=:+***#*********.:--:...---...=+++++++++***##%%#...ssssssssssssssss
...:%%#-+%*++%+==-=*******##****#:..............=++++=++*****#%%%=..ssssssssssssssss
...*%%+-#+++++:::=**********#%##%=sss....:--...:++++++++*****##%%#..ssssssssssssssss
...%%%==+::-=+*#*******=***#=.....sss...-++++++++++++++******##%%#-.ssssssssssssssss
s.-%%%++++==+-=+++*****+***#=.....sss...-***#***++++++***######%%%=.ssssssssssssssss
..-%%%*++++*++=+++**####+=+*#*+*#-sss.....::....++++++**###**##%%%=.ssssssssssssssss
s.-%%%*++++=-----=*#####+#*#####%:ssssssssssss..=++*++*##****##%%%=.ssssssssssssssss
..:%%%#*++++++++++==-#%#-##*#%##*:-=+:...==-..:=+****+*#*****%%%%%-.ssssssssssssssss
...#%%*-::::=++++*%%%%##########*####-...=###=---=+****##***##%%%#:sssssssssssssssss
...+%%#*++++-++++++++*##########*###*:...-###******=+**###**##%%%*..ssssssssssssssss
....%%%*+++=-+**+++++++====+####*#####+=*####**=**-=**#####*#%%%%-..ssssssssssssssss
ss..=%%%***=-++++++**+++++++####*############*+=+*-+*########%%%*...ssssssssssssssss
ssss.*%%%***=**++++++++=.-+*%###*#####*-*#%%#***--+*#####*##%%%%....ssssssssssssssss
ssss.:#%%%******#***+**++*#%%##%*#######%%%%%**==**###%#*#%%%%%:.sssssssssssssssssss
ssss..:#%%%#*****##******######%#####%%%%%%%%#*-+******#%%%%%#-.ssssssssssssssssssss
sssss...*%%%%##***##*****##%%##*==***#%%#===+*++***###%%%%%%#:..ssssssssssssssssssss
sssssss..=%%%%#############*++******#%%%#+***##%%%%%%%%%%%%+....ssssssssssssssssssss
sssssss...:*%%%%###########***+***+**#%%*+*##%%#+%%%%%%%%#:..sssssssssssssssssssssss
sssssss.....-#%%%%%######%****=**********#%%%%%%%%%%%%%#-....sssssssssssssssssssssss
sssssssssss....#%%%%%#####***********##%%%%%%%%%%%%%%%:..sssssssssssssssssssssssssss
sssssssssssssss..=#%%%%%%#%%%###%%%%%%%%%%%%%%%%%%#+..ssssssssssssssssssssssssssssss
sssssssssssssssss...-*#%%%%%%%%%%%%%%%%%%%%%%%#*=.....ssssssssssssssssssssssssssssss
ssssssssssssssssssssss..:-+*#%%%%%%%%%%%#*+=:...ssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssss........................`